name: CICD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        working-directory: . # Çalışma dizinini belirtilen klasöre ayarla
        run: docker build -t berkay1532/wisper:latest .

      - name: Publish image to docker hub
        run: docker push berkay1532/wisper:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull berkay1532/wisper:latest

      - name: Delete old container
        run: docker rm -f wisper-container || true

      - name: Run docker container
        run: docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} --name wisper-container berkay1532/wisper
      - name: Check environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          RABBIT_QUEUE: ${{ secrets.RABBIT_QUEUE }}
          RABBIT_URL: ${{ secrets.RABBIT_URL }}
        run: |
          echo "JWT Secret: $JWT_SECRET"
          echo "Port: $PORT"
          echo "NODE_ENV: $NODE_ENV"
          echo "RABBIT_QUEUE: $RABBIT_QUEUE"
          echo "RABBIT_URL: $RABBIT_URL"
